# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  build_and_test:
    docker:
      - image: cimg/node:12.13.0

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: apt-get update && apt-get install -y libusb-1.0-0

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Build
          command: yarn build
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Audit dependencies
          command: yarn audit
workflows:
  version: 2
  main_workflow:
    jobs:
      - build_and_test
